# Site settings
title: TC Blog
SEOTitle: TC的博客 | TC Blog
header-img: img/home-bg.jpg
email: tautcony@gmail.com
description: "试着记录点东西 | 都是些有的没的"
keyword: "TautCony, @tautcony, TC的博客, TC Blog, 博客, 个人网站"
url: "tautcony.xyz"                     # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

author:
  twitter: tautcony
  github:  tautcony

# SNS settings
RSS: false
# It should be set a proper icon from http://fontawesome.io/icons/ or use a word instead
SocialAccount: [
    {
        title: "github",
        href: "https://github.com/tautcony",
        icon: "fa-github",
        content: ""
    },
    {
        title: "weibo",
        href: "http://weibo.com/3268177885",
        icon: "fa-weibo",
        content: ""
    },
    {
        title: "asciiflow",
        href: "/apps/asciiflow2",
        icon: "fa-terminal",
        content: "",
        in_sidebar: false
    },
    {
        title: "List characters",
        href: "/apps/listcharacters",
        icon: "fa-font",
        content: "",
        in_sidebar: false
    }
]


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","ts","node_modules","apps/material/templates","gulpfile.ts","package.json","README.md","LICENSE"]
anchorjs: true                          # if you want to customize anchor. check out `anchorjs.html`
MathJax: true
particle404: true                       # enable a particle effect 404 page


# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-include-cache]
#octopress-minify-html



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# Disqus settings
disqus_username: tautcony-blog


google-site-verification: "k_t-1fgBwmMc3UsE3yUU5zGQbRN2a0cl-HljKO2odqY"

# Analytics settings
# Baidu Analytics
##ba_track_id:
# Google Analytics
ga_track_id: 'UA-110146907-1'            # Format: UA-xxxxxx-xx



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "专业混吃等死"
sidebar-avatar: /img/avatar-tautcony.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "VCB-Studio",
        href: "http://vcb-s.com/"
    },
    {
        title: "Memo von EFS",
        href: "https://amefs.net/"
    },
    {
        title: "小马哥",
        href: "http://www.vigoss18.com/"
    }
]


excerpt_separator: <!--more-->
incremental: true
